### ISSUE TITLE
Triage: Error uploading descriptor for service

### ISSUE THREAD

**Issue by alecmuffett** [DonnchaC/onion-balance#66]
Hiya!

I'm running on latest / 0.1.8.

The following message is sporadically appearing in the logs, it does not appear to be causing a problem for OnionBalance / the master descriptor is still being published, but I thought I would post it here for consideration of whether this exception is the most appropriate way to trap and handle this issue?

```
2017-05-06 12:00:13,300 [ERROR]: Error uploading descriptor for service xxxxxxx.onion.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/onionbalance/service.py", line 242, in _upload_descriptor
    hsdirs=hsdirs)
  File "/usr/local/lib/python2.7/dist-packages/onionbalance/descriptor.py", line 302, in upload_descriptor
    raise stem.InvalidRequest(response_code, response_content)
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
```

Over the past 4 days, it's happened quite a lot:

```
12:36:48 rig0:onionbalance.d $ grep Server.*not.found onionbalance.log
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "F9EF1F29654CF20F51A30D4BCF04E7D1012F7FDE" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
InvalidRequest: Server "D38D8055A28CB587110EFBC79DD7F26747605E55" not found
```

**Comment by jrandomhacker2** [comment]
here's a quick hack that might help (untested! please give feedback)

$ git diff
diff --git a/onionbalance/service.py b/onionbalance/service.py
index 560ab50..6da4a6b 100644
--- a/onionbalance/service.py
+++ b/onionbalance/service.py
@@ -250,6 +250,9 @@ class Service(object):
                 logger.exception("Error uploading descriptor for service "
                                  "%s.onion.", self.onion_address)
                 break
+            except stem.InvalidRequest:
+                logger.debug("Invalid descriptor received, refreshing consensus")
+                consensus.refresh_consensus()
 
     def descriptor_publish(self, force_publish=False):
         """
