### ISSUE TITLE
Onionbalance fails with stem 1.8.0

### ISSUE THREAD

**Issue by duritong** [DonnchaC/onion-balance#74]
In Fedora Rawhide python3-stem got updated to 1.8.0:

* https://stem.torproject.org/change_log.html#version-1-8
* https://src.fedoraproject.org/rpms/python-stem/c/0ebfedfaf9a76c4bb99f2ce6fea011f6589954fe?branch=master

Now onionbalance fails to build from source in Fedora Rawhide:

* https://koji.fedoraproject.org/koji/taskinfo?taskID=40138595
* https://kojipkgs.fedoraproject.org/work/tasks/8618/40138618/build.log
* https://kojipkgs.fedoraproject.org/work/tasks/8618/40138618/root.log

As now the new python3-stem is used:

```
DEBUG util.py:598:   python3-stem                           noarch  1.8.0-1.fc32       build  529 k
```

And now tests are failing:

```
============================= test session starts ==============================
platform linux -- Python 3.8.1, pytest-4.6.8, py-1.8.0, pluggy-0.13.0
rootdir: /builddir/build/BUILD/onionbalance-0.1.8, inifile: setup.cfg
plugins: mock-1.10.4
collected 48 items
test/test_consensus.py ....                                              [  8%]
test/test_descriptor.py ......xxF...FF                                   [ 37%]
test/test_settings.py ..                                                 [ 41%]
test/test_util.py ............................                           [100%]
=================================== FAILURES ===================================
_______________________ test_generate_service_descriptor _______________________
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0xf6250fb8>
mocker = <pytest_mock.MockFixture object at 0xf62505b0>
    def test_generate_service_descriptor(monkeypatch, mocker):
        """
        Test creation of a fully signed hidden service descriptor
        """
        # Mock the datetime function to return a constant timestamp
        class frozen_datetime(datetime.datetime):
            @classmethod
            def utcnow(cls):
                return datetime.datetime.utcfromtimestamp(UNIX_TIMESTAMP)
        monkeypatch.setattr(datetime, 'datetime', frozen_datetime)
    
        # Patch make_introduction_points_part to return the test introduction
        # point section
        mocker.patch('onionbalance.descriptor.make_introduction_points_part',
                     lambda *_: INTRODUCTION_POINT_PART)
    
        # Test basic descriptor generation.
        signed_descriptor = descriptor.generate_service_descriptor(
            PRIVATE_KEY,
            introduction_point_list=['mocked-ip-list'],
        ).encode('utf-8')
>       stem.descriptor.hidden_service_descriptor.\
            HiddenServiceDescriptor(signed_descriptor, validate=True)
E       AttributeError: module 'stem.descriptor' has no attribute 'hidden_service_descriptor'
test/test_descriptor.py:255: AttributeError
_____________________________ test_sign_descriptor _____________________________
    def test_sign_descriptor():
        """
        Test signing a descriptor
        """
    
        # Test signing an unsigned descriptor
        signed_descriptor = descriptor.sign_descriptor(
            UNSIGNED_DESCRIPTOR, PRIVATE_KEY).encode('utf-8')
>       stem.descriptor.hidden_service_descriptor.\
            HiddenServiceDescriptor(signed_descriptor, validate=True)
E       AttributeError: module 'stem.descriptor' has no attribute 'hidden_service_descriptor'
test/test_descriptor.py:319: AttributeError
_________________ test_descriptor_received_invalid_descriptor __________________
mocker = <pytest_mock.MockFixture object at 0xf6250508>
    def test_descriptor_received_invalid_descriptor(mocker):
        """
        Test invalid descriptor content received from the HSDir
        """
        mocker.patch("onionbalance.descriptor.logger.exception",
                     side_effect=ValueError('InvalidDescriptorException'))
    
        # Check that the invalid descriptor error is logged.
        with pytest.raises(ValueError):
>           descriptor.descriptor_received(u'not-a-valid-descriptor-input')
test/test_descriptor.py:342: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
descriptor_content = 'not-a-valid-descriptor-input'
    def descriptor_received(descriptor_content):
        """
        Process onion service descriptors retrieved from the HSDir system or
        received directly over the metadata channel.
        """
    
        try:
>           parsed_descriptor = stem.descriptor.hidden_service_descriptor.\
                HiddenServiceDescriptor(descriptor_content, validate=True)
E               AttributeError: module 'stem.descriptor' has no attribute 'hidden_service_descriptor'
onionbalance/descriptor.py:246: AttributeError
=============================== warnings summary ===============================
test/test_settings.py::test_parse_config_file_valid
  /builddir/build/BUILD/onionbalance-0.1.8/onionbalance/settings.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    config_data = yaml.load(handle.read())
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
  /usr/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py:139: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
    self._cipher = factory.new(key, *args, **kwargs)
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
test/test_util.py::test_key_decrypt_prompt_encrypted
  /usr/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py:293: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
    return self._cipher.decrypt(ciphertext)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
========= 3 failed, 43 passed, 2 xfailed, 13 warnings in 0.47 seconds ==========
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.kcBquo (%check)
    Bad exit status from /var/tmp/rpm-tmp.kcBquo (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 746, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/python-onionbalance.spec
```

Relates to #69

**Comment by duritong** [comment]
Additionally, there are issues with Python 3.9 - https://bugzilla.redhat.com/show_bug.cgi?id=1792059

**Comment by asn-d6** [comment]
That should be addressed with OBv3. Please test with the new OBv3 repo:
https://github.com/asn-d6/onionbalance
https://gitlab.torproject.org/asn/onionbalance
